use db_dival;

alter table ingredientes auto_increment=1;

insert into ingredientes(Nombre_Ingrediente, Cantidad, Id_UniMed, Id_Proveedor, Precio_Compra, Status)
values('Cacahuate', 5, 2, null, -1, 'D'),
		('Sal', 110, 1, null, -1, 'D'),
        ('Ácido Cítrico', 40, 1, null, -1, 'D'),
        ('Chile de Árbol (molido)', 25, 1, null, -1, 'D'),
        ('Ajo Granulado', 100, 1, null, -1, 'D'),
        ('Cacahuate', 4.25, 2, null, -1, 'D'),
        ('Sal', 80, 1, null, -1, 'D'),
        ('Ácido Cítrico', 45, 1, null, -1, 'D'),
        ('Chile de Árbol (molido)', 20, 1, null, -1, 'D'),
        ('Tortilla', 0.5, 2, null, -1, 'D'),
        ('Pepita', 350, 1, null, -1, 'D'),
        ('Cacahuate', 2.75, 2, null, -1, 'D'),
        ('Sal', 70, 1, null, -1, 'D'),
        ('Ácido Cítrico', 35, 1, null, -1, 'D'),
        ('Chile de Árbol (molido)', 18, 1, null, -1, 'D'),
        ('Haba', 0.5, 2, null, -1, 'D'),
        ('Garbanzo', 1, 2, null, -1, 'D'),
        ('Pepita', 0.25, 2, null, -1, 'D'),
        ('Pasta', 1, 2, null, -1, 'D'),
        ('Aceite', 4, 4, null, -1, 'D'),
        ('Chile-Limón en Polvo', 250, 1, null, -1, 'D'),
        ('Aceite', 170, 3, null, -1, 'D'),
        ('Maíz', 350, 1, null, -1, 'D'),
        ('Sal', 20, 1, null, -1, 'D'),
        ('Queso en Polvo', 10, 1, null, -1, 'D'),
        ('Chipotle en Polvo', 10, 1, null, -1, 'D'),
        ('Adobo en Polvo', 10, 1, null, -1, 'D'),
        ('Queso en Polvo', 14, 1, null, -1, 'D'),
        ('Chipotle en Polvo', 14, 1, null, -1, 'D'),
        ('Adobo en Polvo', 14, 1, null, -1, 'D'),
        ('Chile-Limón', 175, 1, null, -1, 'D'),
        ('Papa', 500, 1, null, -1, 'D'),
        ('Aceite', 1.5, 4, null, -1, 'D'),
        ('Hojuela', 1, 2, null, -1, 'D'),
        ('Azúcar', 1.25, 2, null, -1, 'D'),
        ('Crema San Marcos', 250, 3, null, -1, 'D'),
        ('Vainilla', 250, 3, null, -1, 'D'),
        ('Nescafé Clásico', 40, 1, null, -1, 'D'),
        ('Agua', 250, 3, null, -1, 'D'),
        ('Sal', 35, 1, null, -1, 'D'),
        ('Chile de Árbol', 10, 1, null, -1, 'D'),
        ('Ajo en Polvo', 10, 1, null, -1, 'D'),
        ('Hojuelas de Ajo ', 10, 1, null, -1, 'D'),
        ('Arándado', 750, 1, null, -1, 'D'),
        ('Chile', 60, 1, null, -1, 'D');