use db_dival;

alter table `ventas` auto_increment=1;

insert into `ventas`(Subtotal, Impuesto, Total_Vta, Fecha_Vta, Status)
values(789.2, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
		(68, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (100, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (234, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (1000, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (23, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (50, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (78.9, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (234, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (90, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (123.7, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (900, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (789, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (267, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (100, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (120, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (125, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (290, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (500, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (189, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (890, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (234, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (78, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (10, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (789.2, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (125, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (289, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (278, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (900, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (567, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (34, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (12, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (15, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (90, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (77.56, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D'),
        (28.9, ventas.Subtotal*0.08, ventas.Subtotal+ventas.Impuesto, now(),  'D');